baseURL = 'https://cosmichorror.dev/'
languageCode = 'en-us'
title = 'Cosmic Horror'

theme = 'fuji'
enableEmoji = true
enableRobotsTXT = true

[params]
showReadTime = true
author = 'Cosmic Horror'
sourceURL = 'https://github.com/LovecraftianHorror/cosmichorror'

[markup]

[markup.highlight]
# Gets rid of the ugly background color for code blocks. What else it does? No
# clue...
codeFences = false

[markup.tableOfContents]
# Why yes I'm not a designer. Why do you ask?
startLevel = 1
endLevel = 3

[menu]

[[menu.nav]]
name = "Home"
url = "/"
weight = 1

[[menu.nav]]
name = "About"
url = "/about"
weight = 2

[[menu.link]]
name = "GitHub"
url = "https://github.com/LovecraftianHorror"
weight = 1

[deployment]

[[deployment.targets]]
name = "cosmichorror-deploy"
URL = "gs://cosmichorror.dev"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

[build]
noJSConfigInAssets = true
