baseURL = 'https://cosmichorror.dev/'
languageCode = 'en-us'
title = 'Cosmic Horror'

theme = 'fuji'
enableEmoji = true

[params]
showReadTime = true

[menu]

[[menu.nav]]
name = "Home"
url = "/"
weight = 1


[[menu.link]]
name = "GitHub"
url = "https://github.com/LovecraftianHorror"
weight = 1
