[package]
name = "syntect-chroma-compat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lol_html = "0.3.2"
syntect = "5.0.0"
